### ISSUE TITLE
Home Icon Doesn't respond. 

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#100]
## Expected Behavior
After clicking on Home icon from the menu tray it must be responded and take the user to Home page. 

## Actual Behavior
When user is in profile or in a post then clicking on Home icon from the menu tray doesn't respond. 

## Steps to Reproduce the Problem

  1. Fresh start Steemia app. 
  2. Click on a post or go to your profile or someone else's. 
  3. Open menu tray from left side and click on the Home icon. 
 4. Note after clicking on Home icon it doesn't respond and do not take the user to the Home page. 

## Specifications

  - Version:  Steemia v0.0.4
  - Platform: Android 7.0 
  - Recorded video: https://vimeo.com/277171534

**Comment by jayserdny** [comment]
Hello @ashiqurakash,

I can confirm it is a bug since we never added a function to return to the home page hahahaha. However, we already removed the drawer from sub-pages so you can only see it in main pages.

Thanks :D
