### ISSUE TITLE
Steemia doesn't load

### ISSUE THREAD

**Issue by royachiron** [Steemia/Steemia#103]
![53](https://user-images.githubusercontent.com/23020420/41993286-9f46c2ea-7a53-11e8-8fb5-af007b6a680e.gif)

**Comment by jayserdny** [comment]
Hello @royachiron,

Sorry for this issue, it happens due to expired tokens. However, this issue was corrected in several commits ago and update will be released this week.

Thanks for informing us about this issue :D
