### ISSUE TITLE
Selected currency in setting  not showing the value of the selected currency in post  

### ISSUE THREAD

**Issue by djavalord** [Steemia/Steemia#107]
## Expected Behavior
I expect that when I change the currency to my preferred currency from setting, currencies in post pay out and in my wallet should show the selected currency. 
## Actual Behavior
The currency in post and in my wallet remains in USD after changing to NGN 

## Steps to Reproduce the Problem

  1. Login to steemia using the required details 
  2. Click on the 3 horizontal line at the top left hand side
  3. Select settings from the menu that opens 
4. Click on select currency 
5. Select preferred currency from the list
 6. click OK to apply selection
7. Click the back arrow key at the top left hand side to Go back to home page 
8. You will notice that the currency is still in USD instead of the preferred currency in setting. 
## Specifications

  - Version: android 8.1.0 Oreo 
  - Platform: steemia V 0.0.5
  - Subsystem: Tecno camon X 

### Recording of the bug
https://youtu.be/JN_-IrKkW38

**Comment by jayserdny** [comment]
Hello,

Thanks for your report. I have checked and it is not a bug. Indeed, this option is to manipulate the value shown when you press the payout value of any post. By default, even if it is confusing, the $ sign does not stand for USD (Same for most of the Steem frontends). It stands for the current payout in Steem currency.

However, if you press this value, a popover will pop up and will show the payout value in the currency you've checked in settings.
