### ISSUE TITLE
Same & Wrong Account Activities, Wallet Transaction History Keep Displaying On Every User's Profile

### ISSUE THREAD

**Issue by realrufans** [Steemia/Steemia#108]
<Hr>

#### Expected behavior
The correct **account activity** and **wallet transaction history** should be shown on every user's account.

#### Actual behavior
It keep displaying wrong account activity and transaction history for every user's account clicked.
It happens that , it displays same information for every account on steem blockchain.

#### How to reproduce

* download the app [Steemia](https://play.google.com/store/apps/details?id=com.steemia.steemia)
* Sign in 
* click on search icon then search for any users account.
* click on activity for account activity and wallet for transaction history ( Note the information displayed )
*  Repeat step 3 and step 4 ( search & view another user account this time).

<Hr>

* App version: steemia 0.0.5
* Operating system: android  8.1 Oreo.  Tecno camon X pro

#### Recording Of The Bug
https://m.youtube.com/watch?v=S7Tmh5xioPo

**Comment by jayserdny** [comment]
Hello,

I am closing this one in favor of #106. This bug is the same as #106. Since the profile is not able to load, default data is loaded (as you can notice, the creation date of the user says 'invalid').

Thanks for the report :).

**Comment by realrufans** [comment]
Oh I get it , thanks 👍 best PO
