### ISSUE TITLE
Profiles with no profile image are not loading

### ISSUE THREAD

**Issue by ng-gist** [Steemia/Steemia#109]
## Expected Behavior
When loading a profile with no profile image, it should load fine.

## Actual Behavior
When loading a profile with no profile image, doesn't load properly or at all. It also shows joined date as invalid and no account value. In some cases clicking on other tab doesn't work either.

## Steps to Reproduce the Problem

  1. Find a profile with no image by going into comments of a post.
  2. Click on the profile. This will open profile in new window
  3. A loader will show up with no joined date and account value as blank. In some cases, you can't access any other tabs either.

## Specifications
Profiles used for testing: 
https://steemit.com/@feju
https://steemit.com/@asadxp55

## Recording of Issue
https://www.youtube.com/watch?v=UqUU-amUYZM

  - Version:0.0.5
 - Device : Samsung S8
 - System Operating : 8.0.0 Oreo

**Comment by realrufans** [comment]
Hi mightypanda-x , I think it's same with this  [106](https://github.com/Steemia/Steemia/issues/106)

**Comment by ng-gist** [comment]
It is different, if u see the video, issue only happens with profiles with no image, other profiles work fine. Issue mentioned in that bug happens to profile with images and i cant honestly understand the issue he is describing

**Comment by jayserdny** [comment]
Hello guys,

Both are correct but I will close this one in favor of # 106. Why? Both represent the same issue (I have confirmed that it does not happen only with profiles without profile images but certain profiles. For instance, in the case of #106, the profile did have an image but it failed to load. Hence, it does not only fail when the profile image does not exist.

Thanks.
