### ISSUE TITLE
Steemia Single Page Post Error

### ISSUE THREAD

**Issue by avnigenc** [Steemia/Steemia#13]
A mobile app for the platform Steemit.com. This app is capable of running on iOS and Android sharing the same basecode. Also, this application will include all the features present in the Steemit.com website for those who prefer to use a mobile device instead of a desktop computer.

#### Expected behavior
We need to be able to see the details of the posts on all pages without encountering any problems. We were expecting Trending and Hot pages to work without problems, like the Feed page.

#### Actual behavior
The Trending and Hot pages need to work properly, like the Feed page.
When we click on any post on the feed page and want to see the details, we do not encounter a problem. But when we want to see the details of the posts on the Trending and Hot pages, we get an error. This should not happen.

###### 1-) Install Steemia app.
```
$ sudo npm install -g cordova
$ sudo npm install -g ionic
$ git clone https://github.com/Steemia/Steemia
$ cd Steemia
$ npm install
$ ionic serve --l
```
###### 2-) Click Trending or Hot pages
![treding.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516745926/yza11oxnzymvc2gkb6if.png)

###### 3-) Click the any post
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516745984/ai1vkyokkuthiblbpduu.png)

###### 4-) Error is here
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516746042/ecvlqtbsyhybi1yfh4ch.png)

* Browser: Google Chrome 63.0.3239.132 (Offical) (64 bit) 
* Operating system: Windows 8.1

#### Recording Of The Bug
![](https://media.giphy.com/media/l3diKDbtRJPrbcIla/giphy.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@avnigenc/steemia-single-page-post-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jayserdny** [comment]
resolved in #14
