### ISSUE TITLE
Bug in the created time for feeds

### ISSUE THREAD

**Issue by jayserdny** [Steemia/Steemia#2]
Due to the different timezones, the module moment will fail. Sometimes it will tell the correct posted dated from the current time but, when timezones are different, it will say something like: "in n hours" where n is the numbers of hours remaining "for this post being posted".

**Comment by hsyndeniz** [comment]
Thanks for your contribution. I will fix it with new update. If you have an idea to fix it please share or create pull request 👍

**Comment by jayserdny** [comment]
I can't find a workaround for this as now. What I think is to determine the timezone given by the steem api and calculate the offset between local timezone and steem timezone.

**Comment by jayserdny** [comment]
closed in #14
