### ISSUE TITLE
[Steemia] - Login Error!

### ISSUE THREAD

**Issue by kubragunes** [Steemia/Steemia#33]
#### Steemia
Steemia is a social network app running over the Steem Blockchain. This app will provide the users an enriched user experience plus features commonly encountered in a casually used social media. The goal of this project is to give the community a mobile app where they can do their daily activity in the blockchain.

#### Expected behavior
To login in Steemia application, you need to open the login page in menu.  When the Login With SteemConnect key is pressed on the Login page, the SteemConnect page opens.

#### Actual behavior
When the Login With SteemConnect button is pressed, the Steemconnect home page no longer opens.

#### How to reproduce
You need to download Steemia app from Github
###### How to install
```
$ sudo npm install -g cordova
$ sudo npm install -g ionic
$ git clone https://github.com/Steemia/Steemia
$ cd Steemia
$ npm install
$ ionic serve --l
```
* Browser: Chrome
* Operating system: Windows 10

#### Recording Of The Bug
![](https://media.giphy.com/media/69mVvJq97oeyPsBsjS/giphy.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kubra.gunes/steemia-login-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hsyndeniz** [comment]
Resolved!
