### ISSUE TITLE
A Proposal to Draft a Privacy Policy and Frequently Asked Questions (FAQ) for Steemia

### ISSUE THREAD

**Issue by Pope19** [Steemia/Steemia#34]
After going through the file finder, i discovered that Privacy Policy and FAQ were not present.

Privacy policy is a very important document on any website that details a company's views on information collected from visitors and how it intends to secure that information. It also helps to instill more confidence in the prospective site visitors/app users, and give users an idea of what to expect and what not to expect on the site.

Having an FAQ on the website will increase user confidence as it is often sought after and serves as a source of first communication on any service based website.

Your response in this regard is highly anticipated.

Steemit User @pope1995
Discord @Pope1995#6757

**Comment by jayserdny** [comment]
Hello @Pope19 . Those information will be present on the website (when we release the website). For now, we are mostly focusing in development of the product. However, contributions are always open :)

Thanks.
