### ISSUE TITLE
API calls limit exceeded when rendering post into the feed.

### ISSUE THREAD

**Issue by jayserdny** [Steemia/Steemia#5]
![Screen Shot 2018-01-05 at 5.03.41 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515146646/jpovt3fxqxitev7oqidg.png)

As shown in the image above, the Steemia (old iSteem) app will crash when you try to scroll down up to post number 100.

# Steps to reproduce
- Clone the repo
- Follow steps to install the app given in the repo
- Open the app and scroll down for a while

***
Since the API have a limitation of 100 post depth in the blockchain, the app can be fixed by reducing the number of post loaded by infinite scroll. For example, right now it is being increased by 15 in each iteration which will add up to 105 which is over the limit.

## Where is the error
First thing is to change the value of perPage to 10 which is the initial query of the post.

![Screen Shot 2018-01-05 at 5.11.55 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515147135/jkiu31dmuwxuqrnagta9.png)

![Screen Shot 2018-01-05 at 5.14.49 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515147301/ivywuttuaw2ncqmdo8ny.png)

Then, instead of increase the values of perPage by 15, it should be increased by 10

![Screen Shot 2018-01-05 at 5.12.54 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515147190/bbd06nagtabcwheyy2bh.png)

![Screen Shot 2018-01-05 at 5.15.17 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515147336/uthlhjk376hbbiqdkg9c.png)

Then, a condition should be added in the provider of the data to stop the query when the value of perPage is 100 and initialize another query starting at the 100th post up to the 200th and so on.

![Screen Shot 2018-01-05 at 5.16.50 AM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515147422/txpvozxjpdvap9oo3tuw.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jaysermendez/api-calls-limit-exceeded-when-rendering-post-into-the-feed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by hsyndeniz** [comment]
resolved!
