### ISSUE TITLE
Ability to personalize profile photo and cover photo

### ISSUE THREAD

**Issue by Anyadan** [Steemia/Steemia#62]
#### Components

My contribution is made in regard to the **Steemia** app which is a social media app built based on the Steem block chain. 

My suggestion is about the inclusion of a personalization button for the profile photos.

#### Proposal

My proposal is to make available buttons which would facilitate the ability for one to personalize profile and cover photos. 

This proposal can be implemented by providing a button by the the profile photo and cover photo display areas which would enable one to modify the photos or add one if none is present. 

A pop up should appear after the button is used which would provide options enabling the user to **Capture** a new photo with the phone camera, **Select** a photo from the phone gallery or **Delete** an existing photo. 

#### Mockups / Examples
Once implemented, it should look like this and hence make personalization possible on the app.

![PicsArt_04-17-12.59.00.jpg](https://cdn.utopian.io/posts/faaf95d0250d7c86f2da38b6f26a86dfcfbbPicsArt_04-17-12.59.00.jpg)

Once the personalization button is used, this is what the page should look like. 

![PicsArt_04-17-01.01.36.jpg](https://cdn.utopian.io/posts/2a6a32e9154a420d38e4eb2d5bfd7847c671PicsArt_04-17-01.01.36.jpg)

#### Benefits

Implementation of this suggestion will yield the following benefits:
* Users will be able to personalize their accounts(*in respect to profile photos*). This includes being able to take a photo with the camera, add a photo from the gallery and delete an existing photo. 

* The app will be more reliable and will be utilized more as users would not have to go use the Steemit website.

**Comment by hsyndeniz** [comment]
Thank you for your contribution. It's done!
