### ISSUE TITLE
Website links do not lead users anywhere

### ISSUE THREAD

**Issue by rezamusic881** [Steemia/Steemia#73]
#### <center>Expected behavior</center>
<P>
<div class="text-justify">Supposedly, When the User clicks on the website feature inside the info menu of each user profile, the App will direct the redirect and link directly to the website</div>

#### <center>Actual behavior</center>
<P>
<div class="text-justify">When I try to click on the website features inside the info menu of each user profile, the App does not redirect redirects and links directly to the website.</div>

### <center>How to reproduce</center>

1. Instal App [here](  https://play.google.com/store/apps/details?id=com.steemia.steemia)
2. Run the app.
3. Go to profile and sign in info menu.
4. Click on the user's website link, then the app does not lead you anywhere.

#### <center>Environment</center>
* ###### Device : Redmi Note 5A
* ###### System Operating : 7.1.0 Nougat
* ###### App Version : 0.0.4

***
***

#### <center>Recording Of The Issues</center>

https://youtu.be/uvMnFETA45M

**Comment by jayserdny** [comment]
Hello,

Thanks for your report. This is not a bug. It has not been implemented yet.
