### ISSUE TITLE
Can not install app by playstore link in Redme

### ISSUE THREAD

**Issue by Icramss** [Steemia/Steemia#74]
## Expected Behavior
Should be able to install in playstore link in Redme

## Actual Behavior
Tap on the playstore icon shows only playstore images

## Steps to Reproduce the Problem

  1.go on github stemia
  1. tap redme
  1. Scroll to down and Tap playstore icon

## Specifications

  - Version: android 6.0.1
  - Platform:
  - Subsystem:

**Comment by jayserdny** [comment]
Hello,

Thanks for noticing it. Already fixed it ;)
