### ISSUE TITLE
Comentar with image is not displayed 

### ISSUE THREAD

**Issue by Icramss** [Steemia/Steemia#79]
## Expected Behavior
Commenting with the image can be displayed in the comment box

## Actual Behavior
After commenting using image, image can not be displayed after finished commenting

## Steps to Reproduce the Problem
- open app
- login with your steem account
- Try Tap a post on the homepage
- Try to comment by using the image only
- Tap comment to comment
- Your image comment is not displayed

## Specifications

  - device: 6.0.1

## Recording of the bug

https://youtu.be/dcpd_dN6OhA

**Comment by jayserdny** [comment]
Hello @Icramss,

Thanks for your report. However, at version 0.0.4, this has not been implemented. But, in the next version which is 0.0.5, it has been implemented:

Check here: 

`<div class="message" [innerHTML]="comment.body" autolinker></div>`

https://github.com/Steemia/Steemia/blob/master/src/components/comment/comment.html
