### ISSUE TITLE
The content is not displayed on the profile page after publishing

### ISSUE THREAD

**Issue by Icramss** [Steemia/Steemia#80]
## Expected Behavior
The content created should be displayed after posting on the profile page

## Actual Behavior
The content is not displayed on the profile page. Content can only be seen when Tap is on post. And Content can only be viewed when opened with other applications such as esteem, steemit, busy

## Steps to Reproduce the Problem
- open the app
- Try creating a post
- create a title
- create content with text only
- do not upload image
- create tags
- when done, publication
- Content can not be seen. It only shows the title
- and content can only be seen when Tap on post

## Specifications

Device: 6.0.1

## Recording of the bug
In this recording I just proved it by editing a post that I have published.

https://youtu.be/tV7-fXeyYQc

**Comment by jayserdny** [comment]
Hello @Icramss ,

Not everything is a bug. The fact that the content is not updated after edit the post does not mean that this is a bug. A bug can be that the post was not edited correctly. If you close the profile and open it again, you will see the post updated. Hence, not a bug.
