### ISSUE TITLE
User can't edit or copy paste the text in the comment section. 

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#81]
#### Expected behavior
While writing a comment a comment user should copy or paste or select the text he is writing. 

#### Actual behavior
User can't copy, paste or edit text in the comment section. 

#### How to reproduce
* Download and install Steemia from [Google play store](https://play.google.com/store/apps/details?id=com.steemia.steemia)
* Login with your Steemit account.
* Copy any text from anywhere to find the bug. 
* Try to paste your desire text in the comment section.
* You will find the bug here that user can't edit or copy paste any text in the comment. 

* App version: Steemia v0.0.4
* Operating system: Android 7.0

#### Recording Of The Bug
https://youtu.be/8tVTjggIJMs

**Comment by jayserdny** [comment]
Hello,

Thanks for your report. I have confirmed it and I can reproduce it on my device.
