### ISSUE TITLE
Steemia app opens steemit.com with device browser, taking the user out of steemia. Steem links should be opened in app.

### ISSUE THREAD

**Issue by royachiron** [Steemia/Steemia#82]
## Expected Behavior
I expect to stay in app when trying to access posts that are on the steem blockchain. 
Usually a client/frontend will lead you out of it only when it has content is it not supposed to show. Youtube link should definitely open in relevant app, any app to some steem front end, should open that part of the blockchain in app.  

## Actual Behavior
Steemit.com is launched in browser.

## Steps to Reproduce the Problem

1. Open steemia app
2. Search for "steemitstats" user. Open the user profile.
3. Open latest post of curated links
4. click one of them.
5. Notice how it only asks if to use browsers

## Specifications

  - Version: 0.0.4
  - Platform: Android

GIF of how it behaves on steemia

![34a](https://user-images.githubusercontent.com/23020420/40939029-2b23d0f6-684c-11e8-8466-bea491a8d90c.gif)

GIF how how a reddit client behaves with reddit.com links
![35a](https://user-images.githubusercontent.com/23020420/40939094-5a43f550-684c-11e8-85c2-93c7a8963a4f.gif)

**Comment by jayserdny** [comment]
Hello,

Thanks for your report. However, this is not s bug. Indeed, this is a intended feature since Steemia does not have deep linking (yet, check roadmap)
