### ISSUE TITLE
following/followers list always loses a username/profile when another user is followed on steemia, causing a contradiction between the total number of people following and the usernames/profile in the list. 

### ISSUE THREAD

**Issue by MadwitheSkill** [Steemia/Steemia#83]
* Repository:
https://github.com/Steemia/Steemia
* Project Name: Steemia

#### Expected behavior
After a user is followed on steemit via steemia, it is expected that the user's profile should be added to the list of followed and vice-versa for when a user follows me.

#### Actual behavior
When a user was followed, the number of following increased but checking the list, it is always incomplete by one user profile.

Example: I'm following 20 people on steemit, that count is shown but checking the list only 19 names or profiles are available.
This error can be easily noticed when the following or followers list is not so much. 
Initially this was reasoned to be a delay caused by steemjs but after few days of checking and the error following a pattern it is an error on steemia app.

#### How to reproduce
1.  launch the steemia app
2. login 
3. access app menu by swiping from right to left
4. on menu click "My profile"
5. on profile click info
6. the total number of following and followed is by the side.
7. if the number of following is not so much you can count. 

Another way to confirm this is by following a new user via steemia app only. the following tally increases but the user name is not found when the list is opened or if the username is found,another username will automatically be removed from the list.

#### Test enviroment

* Software: Steemia
* App version: 0.0.4
* Device OS: Android 7.0 Nougat

#### Recording Of The Bug
https://youtu.be/AIBA_MAF5eI
#### GitHub Account
https://github.com/MadwitheSkill

**Comment by jayserdny** [comment]
Thanks for your report. I have confirmed it and will be resolving it for next update 💯

**Comment by MadwitheSkill** [comment]
Alright thanks.

**Comment by jayserdny** [comment]
Fixed 💯
