### ISSUE TITLE
Recent notifications are not showing.

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#84]
## Expected Behavior
When user go to notification section Steemia app should be able to show every recent notifications.

## Actual Behavior
When user go to notification section Steemia app doesn't show the recent updated notifications.

## Steps to Reproduce the Problem

  1. To find this bug first confirm that when your recent notification came.
  2. Then go to Steemia app notification section.
  3. Try to find your recent notification from there.
  4. User won't find his/her recent notifications.
## Specifications

  - Version: Steemia v0.0.4
  - Platform: Android 7.0

**Comment by jayserdny** [comment]
Hello @ashiqurakash ,

Thanks for your report. Sadly, this is something outside our scope since we rely on a third-party service (Busy Inc.) to display the notifications. Hence, there is nothing we can do at the moment other than develop our own solution.

**Comment by ashiqurakash** [comment]
Then what if I contribute it to repository of busy? Can the do something or at least detect this issue as a bug?

**Comment by ashiqurakash** [comment]
Sorry this issue has already been listed in the github repository of busy. Thank you jayserdny for your time I find you always very responsive this is impressive.

**Comment by jayserdny** [comment]
@ashiqurakash At anytime 💯
