### ISSUE TITLE
Post preview not working properly. 

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#86]
## Expected Behavior
When user click on "What's on your mind " to write a post. User should be able to see the preview of his/her post by just clicking on the preview option at the bottom left of the post. 

## Actual Behavior
When user wants to write a post and go to create a new post section by clicking, "What's on your mind" bar at the top of the Steemia home page. Then while writing user can't see the preview of the post simply just click on the preview option. 

## Steps to Reproduce the Problem

  1. From Steemia app home page click on "What's on your mind " to create a new post. 
  2. Write something to see the preview. 
  3. You will notice a unexpected behavior of the preview option. For better understanding of this bug see the recording video. 

## Specifications

  - Version: Steemia v0.0.4
  - Platform: Android 7.0
  - Recorded video:
https://vimeo.com/274350487

**Comment by jayserdny** [comment]
Good finding! And really weird bug since it works when the page is opened from the bottom navigation hehe. Will fix it ASAP since we are about to send an update.

**Comment by ashiqurakash** [comment]
Thank you for confirming it as a bug. And yes I also find it very difficult to explain that how to reproduce. But the recorded video explained it well I guess.

**Comment by jayserdny** [comment]
Fixed 💯
