### ISSUE TITLE
Steemia V 0.0.4 -  A Reply To A Comment And The Main Comment not well aligned.

### ISSUE THREAD

**Issue by realrufans** [Steemia/Steemia#88]
#### Project Information
* Repository:
[Steemia](https://github.com/Steemia/Steemia)

<Hr> 

#### Expected behavior

I expected a threaded Comment  to a post just like the image below.
![Screenshot_20180611-200826_1528746502898.png](https://cdn.steemitimages.com/DQmXG6i618erSMURC1MJrGJoZWn6pbZCxtKdFJRh9MwLhxD/Screenshot_20180611-200826_1528746502898.png)

#### Actual behavior

The reply comment is displaying above the main comment.
![Screenshot_20180611-201359_1528746518577.png](https://cdn.steemitimages.com/DQmc9uXPSmRbck1x9jJWgpWugEjr3UUTCsVMfvSDFfMbJMi/Screenshot_20180611-201359_1528746518577.png)

<Hr>

#### How to reproduce
* Download app from [play store](https://play.google.com/store/apps/details?id=com.steemia.steemia)
* Launch Steemia
* create an account / sign in
* Search for a user's account, then locate a reply to the post comment. You should notice that the reply to the main comment is above the main comment.

- Version: Steemia V 0.0.4
- Operating system: Tecno Camon X pro ( Android 0)

<Hr>

#### Recording Of The Bug

https://m.youtube.com/watch?v=8OXnfuZQECI

<Hr>

#### Githup profile 
[Realrufans](https://github.com/realrufans)

**Comment by jayserdny** [comment]
Hello @realrufans,

This was already fixed but update is not sent yet. However, this was not a bug but a missing feature which we did not implemented before.

Thanks.

**Comment by realrufans** [comment]
Alright thank you
