### ISSUE TITLE
By clicking on reblog in user's own post causes unfinished loading. 

### ISSUE THREAD

**Issue by ashiqurakash** [Steemia/Steemia#90]
## Expected Behavior
After clicking on reblog in user's own post must not be loading forever. 

## Actual Behavior
When user click on the reblog in own post loading does not end. And left the user only one way to get rid of loading which is close the app. 

## Steps to Reproduce the Problem

  1. Fresh start Steemia app and go to your profile. 
  2. Click on any of your post. 
  3. Click on the reblog at the right bottom tray. 
  4. Note the page will keeps loading forever. And the user have to close the app. 

## Specifications

  - Version: Steemia v0.0.4
  - Platform: Android 7.0 
  - Recorded video : https://vimeo.com/274961262

**Comment by hsyndeniz** [comment]
Hi @ashiqurakash
This is because users can not reblog their own posts. I solved this issue but it's not live right now. Just wait for update. Thanks for report.

**Comment by ashiqurakash** [comment]
Oh I see. Thank you for your quick response. I look forward for the next update.
