### ISSUE TITLE
You can still edit post / upload photos in preview mode | editing should be disabled in preview mode

### ISSUE THREAD

**Issue by jelumanao** [Steemia/Steemia#93]
## Expected Behavior
 Uploading a picture or editing contents is disabled when you are in preview mode. 

## Actual Behavior
When you are in preview mode you can still edit contents and upload pictures but it will not reflect yet in the screen until you click the preview mode again. (refer on the video)

## Steps to Reproduce the Problem
* Open Steemia App
* Create a post
* Click Preview mode
* When it is in preview mode, click upload button and try to upload picture or click the Bold, Italic, Highlight button.
* As you can see, nothing happens. But when you see the preview button again, things will reflect.

## Specifications
* Steemia v0.0.4
* Operating system: Android 6.0
* Model: Xiaomi Redmi note 4

https://www.youtube.com/watch?v=2b84gS1C-UQ

**Comment by jayserdny** [comment]
Hello,

Thanks for your report. We will add this as suggestion for the next update :D
