### ISSUE TITLE
cannot be send SBD and STEEM in landscape mode

### ISSUE THREAD

**Issue by shaphir** [Steemia/Steemia#97]
## Expected Behavior
There should be a cancel button and send after I press SBD OR STEEM transfer

## Actual Behavior
When I pressing the transfer in landscape mode, the cancel and send button disappears so I cannot be perform the sending

## Steps to Reproduce the Problem
* Open the app
* Go to wallet
* Then turn on screen rotation on your mobile
* Rotate mobile in landscape position, then press transfer 
* The cancel button and send will disappear from the screen

App version 0.0.4
Operating system using android version 6.0.1

## Recording of the bug on youtebe
https://youtu.be/5xf783-vLiw

**Comment by jayserdny** [comment]
Hello, This issue has been reported before and was added to our TODO list some weeks ago. You can check our TODO list here: https://github.com/Steemia/Steemia/projects/1 Thanks :D
